project:
  type: website
  execute-dir: project
  output-dir: docs
  render: 
    - "*.qmd"

execute:
  freeze: auto

website:
  title: "LTER Scientific Computing Team"
  favicon: images/logos/hex_scicomptools.png
  repo-url: https://github.com/lter/scicomp
  repo-actions: [issue]
  twitter-card: true
  navbar:
    background: primary
    left:
      - text: "Working Group Onboarding"
        menu: 
          - text: "Team Coding"
            href: wg_team-coding.qmd
          - text: "Support Services"
            href: wg_services.qmd
          - text: "Suggested Tools"
            href: wg_tools.qmd
          - text: "Facilitation"
            href: wg_facilitation.qmd
      - text: "Workshops"
        menu:
          - text: "Collaborative Coding with GitHub"
            href: https://lter.github.io/workshop-github/
          - text: "Creating Websites with Quarto"
            href: https://lter.github.io/workshop-quarto/
          - text: "Coding in the Tidyverse"
            href: https://lter.github.io/workshop-tidyverse/
          - text: "Shiny Apps for Sharing Science"
            href: https://njlyon0.github.io/asm-2022_shiny-workshop/
      - text: "Tutorials"
        menu:
         - text: "Store User-Specific Info"
           href: tutorial_json.qmd
         - text: "Connect Google Drive + R"
           href: tutorial_googledrive-pkg.qmd
      - text: "Tips"
        menu: 
          - text: "Organization"
            href: tip_organize.qmd
          - text: "Notebooks vs. Scripts"
            href: tip_notebook-vs-script.qmd
          - text: "File Names"
            href: tip_names.qmd
          - text: "File Paths"
            href: tip_paths.qmd
          - text: "Package Loading"
            href: tip_packages.qmd
          - text: "GitHub & Multiple Products"
            href: tip_github-multi-prods.qmd
    right:
      - text: "Our Team"
        menu:
          - text: "People"
            href: staff.qmd
          - text: "Inernal: Contributing"
            href: internal_contributing.qmd
          - text: "Internal: Team Onboarding"
            href: internal_team-onboard.qmd
          - text: "Internal: WG Setup"
            href: internal_new-wg-setup.qmd
          - text: "Internal: Data Portals"
            href: internal_get-data.qmd
          - text: "Internal: Deploy Shiny Apps"
            href: internal_deploy-shiny.qmd
      - icon: github
        href: https://github.com/lter/scicomp
  page-footer:
    center: "Copyright 2024, LTER Network Office"
    background: secondary
  margin-footer: |
    <img src="images/logos/lter.png" alt="LTER Network logo" width="40%"/>
    <img src="images/logos/nceas.png" alt="NCEAS logo" width="40%"/>

format:
  html:
    theme:
       light: _extensions/lter/lter_scss-theme/theme_lter-edu-light.scss
       dark: _extensions/lter/lter_scss-theme/theme_lter-edu-dark.scss
    mainfont: Open Sans
    toc: true
    link-external-newwindow: true
    link-external-icon: false
