project:
  type: website
  execute-dir: project
  output-dir: docs
  
execute:
  freeze: auto

website:
  title: "LTER Scientific Computing Team"
  favicon: images/logos/hex_scicomptools.png
  repo-url: https://github.com/lter/scicomp
  repo-actions: [issue]
  twitter-card: true
  navbar:
    background: primary
    left:
      - text: "Working Group Onboarding"
        menu: 
          - text: "Team Coding"
            href: wg_team-coding.qmd
          - text: "Support Services"
            href: wg_services.qmd
          - text: "Suggested Tools"
            href: wg_tools.qmd
          - text: "Facilitation"
            href: wg_facilitation.qmd
      - text: "Trainings"
        menu:
         - text: "Workshops"
           href: workshops.qmd
         - text: "Server Tutorial"
           href: tutorial_server.qmd
         - text: "Tutorials"
           href: tutorials.qmd
         - text: "Coding Tips"
           href: best_practices.qmd
      - text: "Portfolio"
        href: portfolio.qmd
    right:
      - text: "Our Team"
        menu:
          - text: "People"
            href: staff.qmd
          - text: "Internal: Team Onboarding"
            href: internal_team-onboard.qmd
          - text: "Internal: WG Setup"
            href: internal_new-wg-setup.qmd
          - text: "Internal: Data Portals"
            href: internal_get-data.qmd
          - text: "Internal: Deploy Shiny Apps"
            href: internal_deploy-shiny.qmd
      - icon: github
        href: https://github.com/lter/scicomp
  page-footer:
    center: "Copyright 2024, LTER Network Office"
    background: secondary
  margin-footer: |
    <img src="images/logos/lter.png" alt="LTER Network logo" width="40%"/>
    <img src="images/logos/nceas.png" alt="NCEAS logo" width="40%"/>

format:
  html:
    theme:
       light: _extensions/lter/lter_scss-theme/theme_lter-edu-light.scss
       dark: _extensions/lter/lter_scss-theme/theme_lter-edu-dark.scss
    mainfont: Open Sans
    toc: true
    link-external-newwindow: true
    link-external-icon: false
