---
title: "Sci Comp Team Onboarding"
---

### Welcome to the Team!

This page contains a quick, cookbook-style set of instructions for new staff on the Scientific Computing Support Team. We are so excited to have you join us and we hope that these instructions are clear and easy-to-follow. Please don't hesitate to reach out if you run into any issues (see the "Our Team" tab of this site) or [post a GitHub issue yourself](https://github.com/NCEAS/scicomp.github.io/issues) on this website's repository!

Listed below are a mix of references and tutorials on concepts we aim to promote to researchers who we support, as well as tools and workflows we use in our team. The goal is to give context about open and reproducible science principles NCEAS is promoting to the scientific community. You will also find information on getting access to the tools that you will need and some general information about working at NCEAS.

---

## Background Reading Material

* Hampton et al 2015. ["The Tao of open science for ecology"](https://doi.org/10.1890/ES14-00402.1)

* Borer et al 2009. ["Effective Data Management"](https://doi.org/10.1890/0012-9623-90.2.205)

* Fegraus et al 2005. ["Maximizing the Value of Ecological Data with Structured Metadata:"](https://doi.org/10.1890/0012-9623%282005%2986[158:MTVOED]2.0.CO;2)

* Heidborn 2008. ["Shedding Light on the Dark Data in the Long Tail of Science"](http://doi.org/10.1353/lib.0.0036)

## Programs & Resources

### GitHub Tutorial

We rely heavily on [GitHub](https://github.com/) for collaboration, and there are a few things you must do to get set up. First, complete the NCEAS GitHub Tutorial [here](https://nceas.github.io/training-git-intro/getting-started-with-git-rstudio.html). This tutorial will help you with getting started with `git` and GitHub using RStudio.

### LTER GitHub Organization

Register (if you have not already) for a personal GitHub account and send your username to Marty to be added to the [LTER GitHub](https://github.com/LTER). This GitHub Organization "owns" the working groups repositories that you will be directly working with so being added to this organization will give you access to needed repositories.

### NCEAS GitHub Enterprise Organization

We use a GitHub Enterprise account to keep track of tasks for the Scientific Computing Support of LTER working groups. To be added to the account you must create an NCEAS account.

Follow the directions outlined [here](https://docs.google.com/document/d/1eoR1oDrCrczgbYHPZU_1szB_2fhzu7EUHnh5nFI3eSg/edit) and send your username to Marty Downs (not the email outlined in the Google Doc).

After you have been added, you will be able to access the [Issues tab of the lter-wg-scicomp GitHub repository](https://github.nceas.ucsb.edu/LTER/lter-wg-scicomp/issues). We use issues on this repository to keep track of tasks and projects as well as who is primarily responsible for a given task and which working group gave us the task initially.

### Slack

We use Slack to communicate with one another throughout the day. To be added to the NCEAS Slack group, register [here](https://slack.nceas.ucsb.edu/). If you already have a slack account, be sure to use the email address you used to register.

Find and join our `#scicomp` channel by clicking the plus sign next to the Channels section. Feel free to join any other channels that you might find interesting! Popular channels include `#diversity`, `#nceas`, and `#social`.

Finally, complete [this short tutorial](https://pages.github.nceas.ucsb.edu/NCEAS/help/chat_room_setup.html) on using Slack.

### NCEAS Server: Aurora

We use the Aurora server (located at aurora.nceas.ucsb.edu) when working with RStudio or JupyterHub. Send an email to help@nceas.ucsb.edu requesting an account mentioning you are working with Marty. Thomas Hetmank or Nick Outin will contact you with directions for setting up an account.

## Recurring NCEAS Meetings

There are a number of recurring meetings that you are encouraged to attend. At your hiring, you should receive an invitation to the NCEAS Google Calendar which has links to all the meeting information. These include Coffee Klatch (a coffee social), Hacky Hours, and Data Science Chats (to name a few).

We also have a team Google Calendar to manage team events. Marty will add you if you have not been already.

## Data Science Background and Tutorials

For good background information on the tools that we use, read through and practice examples of the following chapters from a training we did for postdocs in early 2020: https://science-for-nature-and-people.github.io/2020-data-collab-workshop/2020-02-snapp/index.html

Chapters [3](https://science-for-nature-and-people.github.io/2020-data-collab-workshop/2020-02-snapp/working-on-a-remote-machine.html), [5](https://science-for-nature-and-people.github.io/2020-data-collab-workshop/2020-02-snapp/introduction-to-r-and-rmarkdown.html), [8](https://science-for-nature-and-people.github.io/2020-data-collab-workshop/2020-02-snapp/linux-and-the-command-line.html) are a good background about the tools we use.

Chapters [9](https://science-for-nature-and-people.github.io/2020-data-collab-workshop/2020-02-snapp/data-modeling-tidy-data.html), [10](https://science-for-nature-and-people.github.io/2020-data-collab-workshop/2020-02-snapp/data-cleaning-and-manipulation.html) are a good introduction to data modeling.

### R Self-Assessment

Finally, please complete this [R Training Assessment](https://cosima.nceas.ucsb.edu/r-self-assessment/) to self-assess your skills in R.

Schedule a session with the rest of the team to debrief on your experience.

## HR-related Resources

### Reporting Hours & Kronos

We submit vacation and sick day hours online through [Kronos](https://ucsb.kronos.net/wfc/navigator/logonWithUID). You should receive an email at the start of your employment adding you to an email listserv that will send reminders on when to approve each month's timesheet.

### UC Path

[UC Path](https://www.ucpath.ucsb.edu/) is the online HR portal and can be accessed with your UCSB Net ID. It is where you can access things like your paycheck, next date of paycheck, and benefits (if applicable).
