---
title: "Making a Website with Quarto"
---

## Overview

[Quarto](https://quarto.org/) is a new tool developed by RStudio (the company, not the program) to create a more 'what you see is what you get' editor for creating markdown files and products (e.g., books, websites, etc.). Additionally, it includes a visual editor that allows users to insert headings and embed figures via buttons that are intuitively labeled rather than through somewhat arcane HTML text or symbols. While Quarto is still in its infancy, it is rapidly gathering a following due to the aforementioned visual editor and for the ease with which quarto documents and websites can be created.

## Tutorial Preparation

To follow along with this tutorial you will need to take the following steps:

### 1. Prepare to use GitHub via RStudio

This involves doing all of the [pre-workshop steps](https://lter.github.io/workshop-github/#workshop-preparation) relevant to our "Collaborative Coding with GitHub" workshop.

- Install R
- Install RStudio
- Install Git
- Make a GitHub account
- Connect Git and GitHub
- Celebrate!

### 2. Install [Quarto](https://quarto.org/docs/get-started/)

Before you can make a website with Quarto you will need to install it! This program seamlessly ties into RStudio so you won't need to learn how to navigate a new program.

## Make a New GitHub Repository

{{< include /modules_tutorials/github-create.qmd >}}

## Clone that Repository

{{< include /modules_tutorials/rstudio-clone.qmd >}}

## Create the Website Skeleton

Now we can create the critical website architecture.














---

# BASEMENT

## Create a Quarto Website R Project

{{< include /modules_tutorials/quarto-website_new-proj.qmd >}}

## Preparing Project for Web Deployment

{{< include /modules_tutorials/quarto-website_deploy-prep.qmd >}}

## Adding your Project to GitHub

{{< include /modules_tutorials/github-connect.qmd >}}

## Deploy Website via GitHub

{{< include /modules_tutorials/github-website-deploy.qmd >}}

## Adding Website Content

{{< include /modules_tutorials/quarto-website_add-content.qmd >}}

## Supplementary Information

Quarto is developing at a rapid pace so quality of life changes and new functionalities are introduced relatively frequently. Additionally, Quarto supports user-created "extensions" that can be downloaded in a given project and then used (similar to the way user-developed R packages can be shared) so if you want to do something that Quarto itself doesn't support, chances are you'll be able to find an extension that handles it.

[Quarto's documentation of website creation and formatting](https://quarto.org/docs/websites/) is extremely thorough and is a great resource as you become more comfortable with your new website. We hope this tutorial was useful to you and welcome constructively critical feedback! Please [post an issue](https://github.com/lter/scicomp/issues) with any thoughts for improvement that you have.