---
title: "What is Scientific Computing?"
---

In the most fundamental sense, **scientific computing refers to the process of organizing, managing, and analyzing scientific data using computers**. This process takes place at the interface between several distinct disciplines:

- _Informatics_ provides both a planning framework and operational rules for acquiring, handling, interpreting, and storing the underlying information in a useful and efficient manner
- _Computer science_ and the technologies it produces provide the overarching computational environment, including the core processing "engine" and a means to control it
- Relevant branches of _mathematics_, _statistics_, and _probability_ arm us with numerical models, algorithms, error representations, and other constructs for describing and solving problems quantitatively
- Last but not least, the target science itself (e.g., ecology, geosciences, evolutionary biology, etc.) provides an overall motivation, research paradigm, and conceptual model to guide the analysis

With these many links to other fields, modern scientific computing is now viewed as a field of study unto itself, constantly evolving in step with advances in the disciplines on which it is based.
