---
title: "SciComp Team Onboarding"
---

:::{.callout-caution icon="false"}
### {{< fa house-user >}} Relevant to SciComp Only!

This document is primarily meant for members of the LTER Scientific Computing team.
:::

So, you're a new member of the LTER Scientific Computing (SciComp) team: welcome! **We are excited to have you join us and we hope that the onboarding instructions below are clear and easy-to-follow.**

The goal of this page is to detail which tools we use (and why we use them) but we'll also provide some larger context for LTER's/NCEAS' approach.

## What You Need to Do...

### As Soon As Possible

:::{.panel-tabset}
### Get on GitHub

We rely _heavily_ on [GitHub](https://github.com/), and there are a few things you must do to get set up. See below for details:

1. Create a personal GitHub account
2. **Personalize your GitHub profile**
    - E.g., add a picture, link your ORCiD, pin some of your favorite repositories
    - The point here is to serve as a positive example to working group members as they adopt GitHub best practices
3. Send your GitHub username to Marty Downs to be added to the LTER Network Office GitHub organization ([github.com/lter](https://github.com/lter))
4. Ask Marty to add you the ["network-office" GitHub Team](https://github.com/orgs/lter/teams/network-office)
5. Complete the [LTER GitHub workshop](https://lter.github.io/workshop-github/)
    - There's a lot there so don't try to do it all in one sitting!

### Join Slack

We use Slack to communicate with one another throughout the day. **Register for the NCEAS Slack by clicking [here](https://slack.nceas.ucsb.edu/).** If you already have a Slack account, be sure to use the email address you used previously to register for this organization.

Find and join our `#lter-network-office` channel by clicking the magnifying glass button at the top of the "Channels "section. Feel free to join any other channels that you might find interesting! Popular channels include `#diversity`, `#nceas-residents`, and `#social`.

### Make Office Hours

A key part of the support that our team offers is twice-weekly office hours. We've been using a GoogleSheet for sign-ups so **put the link to that sheet in your email signature**.

The relevant GoogleSheet can be found in the {{< fa shared-drive >}} LNO Shared Drive in the following path: `LTER-LNO-general > data-science-support > scicomp-team_office-hours`.

After an office hour slot has passed, cut/paste that row of the GoogleSheet into the "archive" GoogleSheet (in the same Drive folder) for posterity. Put it in the right sheet for the calendar year so it's easy to summarize for annual reports.

### Get on Aurora

We occasionally use NCEAS' "Aurora" server (located at _aurora.nceas.ucsb.edu_) when working with particularly data-intensive projects. **Send an email to help[at]nceas.ucsb.edu requesting an account** and mention that you are working with the LTER Scientific Computing team. Thomas Hetmank or Nick Outin (NCEAS' IT personnel) will contact you with directions for setting up an account.

Note that we _can_ onboard working groups to using Aurora as well but only a minority of groups' projects actually need/want that access.

### Read Background Lit.

Members of the SciComp team have been part of the authorship team for a couple of great peer-reviewed papers on the philosophical and logistical approaches that we take to support LTER working groups. 

Read the following papers:

- Elmendorf, S.C. _et al._ [Ten Simple Rules for Team Synthesis in Ecological Research](https://besjournals.onlinelibrary.wiley.com/doi/10.1111/2041-210x.70378). **2026**. Methods in Ecology and Evolution.
- Brun, J. _et al._ [Enabling Data-Driven Collaborative and Reproducible Environmental Synthesis Science](https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/2041-210X.70036). **2025**. Methods in Ecology and Evolution

:::

### Within the First 3 Months

:::{.panel-tabset}

### Get Familiar with GitHub Issues

We use GitHub issues _extensively_ to track progress on tasks and make it easier for SciComp team members to (A) collaborate with one another and (B) share progress with working groups in a completely transparent manner. Incidentally this also ensures we act in alignment with our guidance to working groups.

To see our current tasks, check out either [our team's GitHub Project](https://github.com/orgs/lter/projects/11/views/10) or the issues on [this website's GitHub repository](https://github.com/lter/scicomp/issues)

**When you receive a task (or set one for your own improvement as a data scientist), please create an issue for that effort!** Fill out the issue metadata and add track its progress with the GitHub project. We've created a number of issue templates to make creating them a little easier but as you become more familiar with your role, you should feel free to edit those templates as needed.

Check out past issues to get a sense for how issues tend to be scoped and documented and also how various metadata fields have been leveraged.

### Become a Synthesis Fellow

This tab panel title is phrased in a sort of tongue-in-cheek way but ultimately, you will want to gain all the same skills that a graduate of our [Synthesis Skills for Early Career Researchers](https://lter.github.io/ssecr/) (SSECR) course provides early career scientists.

Look through the content on that website and pay special attention to any areas (technical or interpersonal) where you know your skills could stand to be refined. **SciComp team members had a strong presence in the design of these materials and the shape of the course closely mirrors patterns that have worked for past working groups.**

### Do More Reading

Check out these older (but still useful!) publications.

- Hampton, S.E. _et al._ 2015. [The Tao of Open Science for Ecology](https://doi.org/10.1890/ES14-00402.1). **2015**. Ecosphere
- Borer, E.T. _et al._ [Some Simple Guidelines for Effective Data Management](https://doi.org/10.1890/0012-9623-90.2.205). **2009**. Bulletin of the Ecological Society of America
- Fegraus, E.H. _et al._ [Maximizing the Value of Ecological Data with Structured Metadata: An Introduction to Ecological Metadata Language (EML) and Principles for Metadata Creation](https://doi.org/10.1890/0012-9623%282005%2986[158:MTVOED]2.0.CO;2). **2005**. Bulletin of the Ecological Society of America

:::

### Going Forward

:::{.panel-tabset}
### D.R.Y.

"DRY: <u>D</u>on't <u>R</u>epeat <u>Y</u>ourself" is one of the mantras of the working data scientist. When a working group asks for you to do something for them, _the chances are good that one of your predecessors in the SciComp team has already solved a similar problem!_

Glance through the [repositories on the LTER GitHub organization](https://github.com/orgs/lter/repositories) in order to become generally familiar with the code we've written for (and with) groups in the past. Feel free to copy/paste old code written by the team if it saves you some redundant setup effort.

### Plant Seeds

One of the reasons why groups _adore_ working with our team is that our solutions often solve not just the problem at hand, but several related problems in the future too! **Where possible, try to make your solutions as useful as possible to 'future you' or future team members.** Such effort also helps working groups gain and apply new skills both within their working group and in their careers outside of the working group!

The title of this tabset panel comes from a 1950s American author (though it is often attributed to famous Greek philosophers). To paraphrase:

> A society becomes great when people plant the seeds for trees under which they know they will never sit

This is a little grandiose but applies to your work with the SciComp team and, in our opinion, the whole endeavor of reproducible, open science!

### Prioritize Your Development!

Pursuing chances to grow your skillset (whether it be interpersonal or technical), is a benefit both to the SciComp team right now and to your development as a data scientist! **As you increase the breadth and depth of your skills, you'll be better-equipped to help working groups.**

Some past SciComp members have opened GitHub issues to track their own skill development! Such issues can be found as sub-issues under the "[SciComp] Improve Working Group Support" issue ([\#30](https://github.com/lter/scicomp/issues/30)). Check them out for inspiration if desired.

:::
