
## Workshops & Trainings

With those workshops, our team aim at helping you to further develop skills in reproducible data science to enable your team to better collaborate and efficiently tackle data and analytical challenges. It is sometimes the case that your working group wants to become more familiar (or get a refresher) on a tool you'd like to include in your group's workflow. To that end **we can design and offer workshops on a selection of data science tools.** Our current workshops catalog includes a [Collaborative Coding with GitHub](https://nceas.github.io/scicomp.github.io/workshops.html#collaborative-coding-with-github), a [primer on the `tidyverse` R packages](https://nceas.github.io/scicomp.github.io/workshops.html#coding-in-the-tidyverse), and a [review of the fundamentals of R Shiny apps](https://nceas.github.io/scicomp.github.io/workshops.html#r-shiny-apps-for-sharing-science). Our past workshops are summarized [here](https://nceas.github.io/scicomp.github.io/workshops.html) and we are happy to offer new workshops if your group wants a workshop on something within our knowledge base. These workshops are typically done remotely (we can also accommodate time during one of your meeting) and last 2-3 hours but we can be flexible with that timing depending on your group's needs.

Similarly, we also have been creating more **'go at your own pace'-style tutorials** that can be accessed [here]((https://nceas.github.io/scicomp.github.io/tutorials.html)). These tutorials are usually smaller in scope than workshops but are still built to maximize value to your group either as review or first contact with a given subject. As with the workshops, we are happy to create new tutorials if something comes up for your team so please reach out and we can discuss further!